version: '2.1'

services:
  db:
    image: postgres:11.5
    restart: always
    env_file: .env
    ports:
      - 5432:5432
#    volumes:
#      - ./db_init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
#  zoo1:
#    image: zookeeper:3.4.9
#    hostname: zoo1
#    ports:
#      - "2181:2181"
#    env_file: .env
#    volumes:
#      - ./zk-single-kafka-single/zoo1/data:/data
#      - ./zk-single-kafka-single/zoo1/datalog:/datalog
#  kafka1:
#    image: confluentinc/cp-kafka:5.3.0
#    hostname: kafka1
#    ports:
#      - "9092:9092"
#    env_file: .env
#    volumes:
#      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
#    depends_on:
#      - zoo1
