create schema config;

CREATE TABLE config.user
(
    user_id                   bigint  not null generated by default as identity primary  key,
    name                      text CHECK (char_length(name) <= 255),
    user_name                 text CHECK (char_length(user_name) <= 255),
    password                  text CHECK (char_length(password) <=512),
    created_by_id             bigint,
    creation_date             timestamp without time zone,
    modified_by_id            bigint,
    modification_date         timestamp without time zone,
    password_expiration_date  timestamp without time zone,
    active                    boolean      DEFAULT true,
    sso_enabled               boolean      DEFAULT false,
    last_login_datetime       timestamp with time zone
);
-- create unique index partner_name_ndx on mdata.partner(partner_name);
create unique index user_name_ndx on config.user(user_name);


