create table if not exists config.social_app_type
(
    social_app_type  text not null primary key
);



create table if not exists config.social_app
(
    app_id                      bigint  not null generated by default as identity,
    social_app_type             text not null,
    client_id                   text not null,
    secret                      text not null,
    callback_url                text,
    primary key (app_id),
    foreign key (social_app_type) references config.social_app_type(social_app_type) ON DELETE CASCADE
);


create table if not exists config.user_social
(
    user_social_id              bigint not null generated by default as identity primary  key,
    app_id                      bigint not null,
    user_id                     bigint not null,
    meta_data                   jsonb,
    access_token                text,
    secret_token                text,
    lookback_window             bigint not null, -- days
    foreign key(app_id) references config.social_app(app_id),
    foreign key (user_id) references config.user(user_id)
);


